-- Password =>>>>> test
insert into app_user(email,firstname,lastname,birthday_date,password,role) values ('superman@world.com','super','man','2000-01-01','$2a$10$XiBW5uqhQ5EBjIL.G6kxAO/E406p.RXJ30jKq0cwEccUrmfmuJG7q','ROLE_USER');
insert into app_user(email,firstname,lastname,birthday_date,password,role) values ('youssra@tcl.com','Youssra','TIGE','2000-01-01','$2a$10$XiBW5uqhQ5EBjIL.G6kxAO/E406p.RXJ30jKq0cwEccUrmfmuJG7q','ROLE_ADMIN');
insert into app_user(email,firstname,lastname,birthday_date,password,role) values ('arnaud@tcl.com','Arnaud','CHENIER','2000-01-01','$2a$10$XiBW5uqhQ5EBjIL.G6kxAO/E406p.RXJ30jKq0cwEccUrmfmuJG7q','ROLE_ADMIN');
insert into app_user(email,firstname,lastname,birthday_date,password,role) values ('fabien@tcl.com','Fabien','LAURETTE','2000-01-01','$2a$10$XiBW5uqhQ5EBjIL.G6kxAO/E406p.RXJ30jKq0cwEccUrmfmuJG7q','ROLE_ADMIN');
-- alimentation movie
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Ryan Gosling, Dave Bautista, Robin Wright, Mark Arnold', 8, 'ACTION', 'Young Blade Runner discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who''s been missing for thirty years.', 164, 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg', 'tt1856101', 463964, '2017-01-01', 'Blade Runner 2049');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos', 8.1, 'ACTION', 'A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.', 117, 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'tt0083658', 695428, '1982-01-01', 'Blade Runner');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Ray Romano, John Leguizamo, Denis Leary, Goran Visnjic', 7.5, 'ANIMATION', 'Set during the Ice Age, a sabertooth tiger, a sloth, and a wooly mammoth find a lost human infant, and they try to return him to his tribe.', 81, 'https://m.media-amazon.com/images/M/MV5BMmYxZWY2NzgtYzJjZC00MDFmLTgxZTctMjRiYjdjY2FhODg3XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg', 'tt0268380', 443268, '0200-01-01', 'Ice Age');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Eunice Cho, Karen Disher, Harrison Fahn, Maile Flanagan', 6.9, 'ANIMATION', 'When Sid''s attempt to adopt three dinosaur eggs gets him abducted by their real mother to an underground lost world, his friends attempt to rescue him.', 94, 'https://m.media-amazon.com/images/M/MV5BMTMzNDkzMTcyOV5BMl5BanBnXkFtZTcwNDIzMjM2MQ@@._V1_SX300.jpg', 'tt1080016', 224642, '0200-01-01', 'Ice Age: Dawn of the Dinosaurs');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Stephanie Beatriz, Robert Cardone, Neil deGrasse Tyson, Adam Devine', 5.7, 'ANIMATION', 'When Scrat''s acorn sends an asteroid to Earth, the Herd must find a way to stop the asteroid from hitting Earth with the help of a returning friend.', 94, 'https://m.media-amazon.com/images/M/MV5BMzFjYWM5NzgtMGIwMi00MmE3LWE3NTgtNmIwMmRkNmFmYzJkXkEyXkFqcGdeQXVyNDQ2MTMzODA@._V1_SX300.jpg', 'tt3416828', 57286, '0201-01-01', 'Ice Age: Collision Course');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow', 7.9, 'ACTION', 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.', 126, 'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg', 'tt0371746', 941171, '0200-01-01', 'Iron Man');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce', 7.1, 'ACTION', 'When Tony Stark''s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.', 130, 'https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg', 'tt1300854', 757267, '0201-01-01', 'Iron Man 3');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Tobey Maguire, Willem Dafoe, Kirsten Dunst, James Franco', 7.3, 'ACTION', 'When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.', 121, 'https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SX300.jpg', 'tt0145487', 689242, '0200-01-01', 'Spider-Man');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll', 7.3, 'ACTION', 'Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.', 117, 'https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg', 'tt0478970', 572212, '0201-01-01', 'Ant-Man');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Donnie Yen, Simon Yam, Lynn Xiong, Hiroyuki Ikeuchi', 8, 'ACTION', 'During the Japanese invasion of China, a wealthy martial artist is forced to leave his home when his city is occupied. With little means of providing for themselves, Ip Man and the remaining members of the city must find a way to survive.', 106, 'https://m.media-amazon.com/images/M/MV5BNTFmMjM3M2UtOTIyZC00Zjk3LTkzODUtYTdhNGRmNzFhYzcyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'tt1220719', 211913, '0200-01-01', 'Ip Man');
INSERT INTO public.movie ( actors, average_rating, category, description, duration, image_url, imdb_id, number_of_votes, release_date, title) VALUES ('Mounïm Kbab, Mustapha Hansali, Hicham Moussoune, Abdelhak Zhayra', 7.3, 'DRAMA', 'A group of children living on the street leave their gang, prompting retribution from the gang''s leader. After one of the children dies, the rest try to come up with the resources to give their friend a proper burial.', 90, 'https://m.media-amazon.com/images/M/MV5BMTg5Nzg5MTIwOF5BMl5BanBnXkFtZTcwODI2ODc4Mw@@._V1_SX300.jpg', 'tt0260688', 2582, '0200-01-01', 'Ali Zaoua: Prince of the Streets');
-- alimentation serie
insert into serie(imdb_id,title,description,image_url,category,actors,start_year,end_year,number_of_season,number_of_episode,status_serie,average_rating, number_of_votes) values('tt0108778','Friends','Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan','https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg','ROMANCE','Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc','1994','2004','10',null,'FINISH','8.9','828187');
insert into serie(imdb_id,title,description,image_url,category,actors,start_year,end_year,number_of_season,number_of_episode,status_serie,average_rating, number_of_votes) values('tt0944947','Game of thrones','Neuf familles nobles rivalisent pour le contrôle du Trône de Fer dans les sept royaumes de Westeros','https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg','ACTION','Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington','2011','2019','8',null,'FINISH','9.3','773746');
insert into serie(imdb_id,title,description,image_url,category,actors,start_year,end_year,number_of_season,number_of_episode,status_serie,average_rating, number_of_votes) values('tt0455275','Prison break','Due to a political conspiracy an innocent man is sent to death row and his only hope is his brother who makes it his missi ...','https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_SX300.jpg','ACTION','Dominic Purcell, Wentworth Miller, Robert Knepper, Amaury Nolasco','2005','2017','5',null,'FINISH','8.3','475921');
-- Visionnage Serie de superman@world.com
insert into serie_viewing(app_user_jpa_user_id,serie_jpa_serie_id,status,current_season,current_episode,date_last_action) values (1,1,'WATCHED',5,2,'2021-03-01 21:36:15.108');
insert into serie_viewing(app_user_jpa_user_id,serie_jpa_serie_id,status,current_season,current_episode,date_last_action) values (1,2,'TO_WATCH',2,1,'2021-03-01 21:36:15.108');
-- Visionnage Serie de fabien@tcl.com
insert into serie_viewing(app_user_jpa_user_id,serie_jpa_serie_id,status,current_season,current_episode,date_last_action) values (4,1,'WATCHED',5,2,'2021-03-01 21:36:15.108');
insert into serie_viewing(app_user_jpa_user_id,serie_jpa_serie_id,status,current_season,current_episode,date_last_action) values (4,2,'TO_WATCH',2,1,'2021-03-01 21:36:15.108');
-- Visionnage Movie
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-01 00:00:00', 'TO_WATCH', 4, 1);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-01 00:00:00', 'TO_WATCH', 4, 2);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-01 00:00:00', 'TO_WATCH', 1, 1);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-01 00:00:00', 'TO_WATCH', 1, 2);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-06 14:13:19.678', 'TO_WATCH', 4, 3);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-06 14:15:08.196', 'TO_WATCH', 4, 4);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-06 14:24:07.894', 'TO_WATCH', 4, 9);
INSERT INTO public.movie_viewing ( date_modified, status, user_id, movie_id) VALUES ('2021-03-06 14:30:16.53', 'TO_WATCH', 4, 11);
