######## Fichier configuration de l'application ######
spring:
  application:
    name: tcl
  profiles:
    active: local
  jta:
    enabled: false
  jpa:
    open-in-view: false
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    mapping-resources:
      - META-INF/common.orm.hbm.xml
      - META-INF/person.orm.hbm.xml
    show-sql: true
  cache:
    jcache:
      config: classpath:cache/ehcache.xml
